name: FlexApp Admin Backend Auto-Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    - name: Deploy to Server with Password
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          mkdir -p $DEPLOY_PATH &&
          cd $DEPLOY_PATH &&
          git pull &&
          npm install &&
          npm run build &&
          pm2 restart all
        "
